fix(sync-version-with-upstream): Fix missing Leptonica part commit-tag replace logic
Signed-off-by: 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>

diff --git a/.github/workflows/sync-version-with-upstream.yml b/.github/workflows/sync-version-with-upstream.yml
--- a/.github/workflows/sync-version-with-upstream.yml
+++ b/.github/workflows/sync-version-with-upstream.yml
@@ -60,7 +60,7 @@ jobs:
               exit 2
             fi
 
-            printf 'Info: Filtering out stable release tags from the release tags...\n'
+            printf 'Info: Filtering out stable release tags from the Tesseract release tags...\n'
             grep_opts=(
               # Show lines that don't match the regexp
               --invert-match
@@ -75,12 +75,12 @@ jobs:
               grep "${grep_opts[@]}" <<<"${release_tags}"
               )"; then
               printf \
-                'Error: Unable to filter out stable release tags from the release tags.\n' \
+                'Error: Unable to filter out stable release tags from the Tesseract release tags.\n' \
                 1>&2
               exit 2
             fi
 
-            printf 'Info: Determining the latest stable release tag...\n'
+            printf 'Info: Determining the latest stable Tesseract release tag...\n'
             head_opts=(
               --lines=1
             )
@@ -90,24 +90,24 @@ jobs:
                 <<<"${stable_release_tags}"
               )"; then
               printf \
-                'Error: Unable to determine the latest stable release tag.\n' \
+                'Error: Unable to determine the latest stable Tesseract release tag.\n' \
                 1>&2
               exit 2
             fi
             printf \
-              'Info: Latest stable release tag determined to be %s.\n' \
+              'Info: Latest stable Tesseract release tag determined to be %s.\n' \
               "${latest_stable_release_tag}"
 
             printf \
-              'Info: Determining the latest stable release version...\n'
+              'Info: Determining the latest stable Tesseract release version...\n'
             # Upstream uses verbatim version string as the name of the release tag
             latest_stable_release_version="${latest_stable_release_tag}"
             printf \
-              'Info: The latest stable release version determined to be "%s".\n' \
+              'Info: The latest stable Tesseract release version determined to be "%s".\n' \
               "${latest_stable_release_version}"
 
             printf \
-              'Info: Replacing the version string in the Snapcraft recipe...\n'
+              'Info: Replacing the Tesseract version string in the Snapcraft recipe...\n'
             sed_opts=(
               # Transform file in-place
               --in-place
@@ -120,7 +120,104 @@ jobs:
             )
             if ! sed "${sed_opts[@]}" snap/snapcraft.yaml; then
               printf \
-                'Error: Unable to replace the version string in the Snapcraft recipe.\n' \
+                'Error: Unable to replace the Tesseract version string in the Snapcraft recipe.\n' \
+                1>&2
+              exit 2
+            fi
+
+            printf 'Info: Querying the Leptonica GitHub release information...\n'
+            curl_opts=(
+              # Don't print progress meter but still show errors
+              --silent
+              --show-error
+
+              # Follow redirection
+              --location
+            )
+            if ! lept_github_releases_raw="$(
+              curl \
+                "${curl_opts[@]}" \
+                https://api.github.com/repos/DanBloomberg/leptonica/releases
+              )"; then
+              printf \
+                'Error: Unable to query the Leptonica releases information.\n' \
+                1>&2
+              exit 2
+            fi
+
+            printf 'Info: Querying the release tags from the Leptonica GitHub release information...\n'
+            jq_opts=(
+              # Show raw strings without quoting
+              --raw-output
+            )
+            if ! lept_release_tags="$(
+              jq \
+                "${jq_opts[@]}" \
+                .[].tag_name \
+                <<<"${lept_github_releases_raw}"
+              )"; then
+              printf \
+                'Error: Unable to query the release tags from the Leptonica GitHub release information.\n' \
+                1>&2
+              exit 2
+            fi
+
+            printf 'Info: Filtering out stable release tags from the Leptonica release tags...\n'
+            grep_opts=(
+              # Show lines that don't match the regexp
+              --invert-match
+
+              # Use Extended Regular Expressions(ERE)
+              --extended-regexp
+
+              # Match all non stable release tags
+              # As of 2024/8/23 Leptonica doesn't seem to release
+              # non-stable releases, we filter out generic names
+              # instead
+              --regexp='(alpha|beta|dev|rc)'
+            )
+            if ! lept_stable_release_tags="$(
+              grep "${grep_opts[@]}" <<<"${lept_release_tags}"
+              )"; then
+              printf \
+                'Error: Unable to filter out stable release tags from the Leptonica release tags.\n' \
+                1>&2
+              exit 2
+            fi
+
+            printf 'Info: Determining the latest stable Leptonica release tag...\n'
+            head_opts=(
+              --lines=1
+            )
+            if ! lept_latest_stable_release_tag="$(
+              head \
+                "${head_opts[@]}" \
+                <<<"${lept_stable_release_tags}"
+              )"; then
+              printf \
+                'Error: Unable to determine the latest stable Leptonica release tag.\n' \
+                1>&2
+              exit 2
+            fi
+            printf \
+              'Info: Latest stable Leptonica release tag determined to be %s.\n' \
+              "${lept_latest_stable_release_tag}"
+
+            printf \
+              'Info: Replacing the Leptonica source commit-tag in the Snapcraft recipe...\n'
+            yq_opts=(
+              # Update file in-place
+              --inplace
+
+              # Set exit status if errors are occurred
+              --exit-status
+            )
+            if ! yq \
+              "${yq_opts[@]}" \
+              ".parts.leptonica.source-tag = \"${lept_latest_stable_release_tag}\"" \
+              snap/snapcraft.yaml; then
+              printf \
+                'Error: Unable to replace the Leptonica source commit-tag in the Snapcraft recipe.\n' \
                 1>&2
               exit 2
             fi
